version: '3.8'

services:
  nextjs:
    image: lucaspscheidtunc/tarefa-app:1.0
    container_name: tarefa-app
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    networks:
      - mysql-net

networks:
  mysql-net:
    external: true